package com.outbottle.genericdao.model.entities;
// Generated May 9, 2012 6:08:09 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name="test"
    ,catalog="test"
)
public class Test  implements java.io.Serializable {


     private Long testId;
     private String name;
     private char archived;
     private String username;

    public Test() {
    }

    public Test(String name, char archived,String username) {
       this.name = name;
       this.archived = archived;
       this.username = username;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="test_id", unique=true, nullable=false)
    public Long getTestId() {
        return this.testId;
    }
    
    public void setTestId(Long testId) {
        this.testId = testId;
    }
    
    @Column(name="name", nullable=false, length=5)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column (name="username",nullable=false,length=10)
    public String getUsername(){
        return this.username;
    }
    public void setUsername(String username){
        this.username = username;
    }
    @Column(name="archived", nullable=false, length=1)
    public char getArchived() {
        return this.archived;
    }
    
    public void setArchived(char archived) {
        this.archived = archived;
    }

}
